[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap = "4.5.50"
reqwest = "0.12.24"
serde.workspace = true
serde_json.workspace = true
tokio = "1.48.0"
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
